# Generated by Django 4.2.2 on 2023-06-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('CabeceraId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_TipoDocumento',
            fields=[
                ('TipodocumentoId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('detalleId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('CabeceraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.cabecera')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_Persona',
            fields=[
                ('PersonaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipodocumentoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.catalogo_tipodocumento')),
            ],
        ),
    ]
