# Generated by Django 4.2.2 on 2023-06-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_cabeceraprofesores_detallealumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='CabeceraId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='apirest.cabecera'),
        ),
    ]
